INSERT INTO USER (ID, NAME, EMAIL, PASSWORD)
VALUES (1111, 'admin', 'admin@gmail.com', '$2a$10$gDc4SqW9Y9VsPNDV63krR.yNGhVkVBdRFUU9GUV6VhuSfi6neNr8K');

INSERT INTO USER_ROLES (USER_ID, ROLES)
VALUES (1111, 'USER');

INSERT INTO USER_ROLES (USER_ID, ROLES)
VALUES (1111, 'ADMIN');

INSERT INTO USER (ID, NAME, EMAIL, PASSWORD)
VALUES (2222, 'user', 'user@gmail.com', '$2a$10$1ok3CeCSVd/GyiguPQwAS.Nw3tvOoBcX0n4ZCn9wV5mpFy3Z74Z2.');

INSERT INTO USER_ROLES (USER_ID, ROLES)
VALUES (2222, 'USER');